main : spellinteracttest.Main

name : spellinteract

version : 1.1.0


api-version: 1.16

depend: [ProtocolLib]

author : ykh

description : test

commands :
  spi:
    description: spi
    usage: /spi