main : spellinteracttest.Main

name : spellinteract

version : 1.1.0


api-version: 1.17

# depend: [ProtocolLib]

author : ykh

description : test

commands :
  spi:
    description: spi
    usage: /spi
  party:
    description: party
    usage: /party
  파티:
    description: 파티
    usage: /파티
  duel:
    description: duel
    usage: /duel
  packetrecord:
    description: packetrecord
    usage: /packetrecord
    aliases: [pr]
